### ISSUE TITLE
Create VBA coding standard document

### ISSUE THREAD

**Issue by peterennis** [kinsidar/Association-Contacts#13]

**Comment by kinsidar** [comment]
@peterennis 

Where would I add the standard document? Would I comment it in either `aeAssociationContacts_ChangeLog` module or `mod_DatesTimes` module?

**Comment by peterennis** [comment]
I suggest creating an external CODING-STANDARD.md file in the GitHub project root. It is not related to any particular database project.

**Comment by kinsidar** [comment]
Added the markdown file, will add to it as we go.
