### ISSUE TITLE
Moving SVIPDB Documentation

### ISSUE THREAD

**Issue by kinsidar** [kinsidar/Association-Contacts#29]
Currently we host the SVIPDB documentation on this repository, resulting in many commits that are not related to Association-Contacts.

Should we move the documentation to a fork of SVIPDB on github?

@peterennis

**Comment by peterennis** [comment]
@kinsidar, Move the documentation to a permanent branch on VSTS. Work out what is needed.
Document it.

**Comment by kinsidar** [comment]
@peterennis 

I think the problem with that is that since we are using github pages to host the documentation page, if we move it to VSTS branch we would not be able to do that. 

Would it be feasible to create a repository just for SVIPDB documentation page?

**Comment by peterennis** [comment]
@kinsidar 
Look at this:
https://marketplace.visualstudio.com/items?itemName=hoyt-tian.gitbook-kit

See if it works well with VS code.

**Comment by peterennisrda** [comment]
@kinsidar, You are invited to SVIPDOC as a collaborator. Put the documentation there.

**Comment by kinsidar** [comment]
Thanks! Will move the documentation there.
